# -*- coding: utf-8 -*-
"""dl5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjth8VP1WEDrtmeVej-pUH4LacHFTkg_
"""

!pip install optuna
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import optuna
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
np.random.seed(42)
samples = 2000
antennas = 4
X = np.random.randn(samples, antennas)
H = np.random.randn(antennas, antennas)
y = np.dot(X, H) + 0.1*np.random.randn(samples, antennas)
scaler = StandardScaler()
X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)
def build_model(trial):
model = Sequential()
units1 = trial.suggest_int("units_layer1", 32, 128)
units2 = trial.suggest_int("units_layer2", 32, 128)
dropout = trial.suggest_float("dropout", 0.1, 0.5)
lr = trial.suggest_float("learning_rate", 1e-4, 1e-2)
model.add(Dense(units1, activation='relu', input_shape=(4,)))
model.add(Dropout(dropout))
model.add(Dense(units2, activation='relu'))
model.add(Dense(4))
optimizer = Adam(learning_rate=lr)
model.compile(
optimizer=optimizer,
loss='mse',
metrics=['mae']
)
return model
def objective(trial):
model = build_model(trial)



    history = model.fit(
        X_train,
        y_train,
        epochs=20,
        batch_size=32,
        verbose=0
    )
    loss, mae = model.evaluate(X_test, y_test, verbose=0)
    return loss
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=20)

print("Best Hyperparameters:")
print(study.best_params)
best_params = study.best_params
model = Sequential()
model.add(Dense(best_params["units_layer1"], input_shape=(4,)))
model.add(Dropout(best_params["dropout"]))
model.add(Dense(best_params["units_layer2"], activation='relu'))
model.add(Dense(4))
optimizer = Adam(learning_rate=best_params["learning_rate"])
model.compile(
    optimizer=optimizer,
    loss='mse',
    metrics=['mae']
)




history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)
loss, mae = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test MAE:", mae)
predictions = model.predict(X_test)

print("Sample Predictions:")
print(predictions[:5])
plt.figure()
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Training vs Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend(["Train", "Validation"])
plt.show()